import { QuestionDefinition } from "./types";

export const QUESTIONNAIRE_SCHEMA_VERSION = "2026-05-02.v1";

export const questionnaire: QuestionDefinition[] = [
  {
    id: "primary_goal",
    section: "goals",
    title: "What are your top goals?",
    description:
      "Pick up to 3. Order matters — your first pick anchors the plan, the others shape it.",
    maxSelections: 3,
    required: true,
    options: [
      { value: "sleep", label: "Better sleep" },
      { value: "energy", label: "More energy" },
      { value: "stress", label: "Stress support" },
      { value: "cognitive_performance", label: "Sharper focus and mental performance" },
      { value: "cognitive_longevity", label: "Long-term brain health" },
      { value: "performance", label: "Exercise performance and recovery" },
      { value: "general_nutrition", label: "General nutritional coverage" },
      { value: "immune_support", label: "Immune support" },
      { value: "gut_support", label: "Gut support" },
      { value: "joint_mobility", label: "Joint mobility and recovery" },
      { value: "healthy_aging", label: "Healthy aging (general longevity)" },
    ],
  },
  {
    id: "age_band",
    section: "safety",
    title: "Which age range fits you?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "under_18", label: "Under 18" },
      { value: "18_29", label: "18 to 29" },
      { value: "30_44", label: "30 to 44" },
      { value: "45_59", label: "45 to 59" },
      { value: "60_69", label: "60 to 69" },
      { value: "70_79", label: "70 to 79" },
      { value: "80_plus", label: "80 or older" },
    ],
  },
  {
    id: "sex",
    section: "safety",
    title: "What sex were you assigned at birth?",
    description: "Used only for supplement safety and deficiency risk logic.",
    maxSelections: 1,
    required: true,
    options: [
      { value: "female", label: "Female" },
      { value: "male", label: "Male" },
      { value: "intersex", label: "Intersex" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
  },
  {
    id: "pregnant_or_breastfeeding",
    section: "safety",
    title: "Are you currently pregnant or breastfeeding?",
    maxSelections: 1,
    required: true,
    showWhen: [
      {
        questionId: "sex",
        includes: ["female", "intersex", "prefer_not_to_say"],
      },
    ],
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "medication_profile",
    section: "safety",
    title: "Do you take prescription medication?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "no", label: "No" },
      { value: "some_rx", label: "Yes, one or a few" },
      { value: "polypharmacy", label: "Yes, several medications" },
    ],
  },
  {
    id: "blood_thinner_use",
    section: "safety",
    title: "Do you take a blood thinner or have a known bleeding risk?",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "medication_profile", excludes: ["no"] }],
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "statin_use",
    section: "safety",
    title: "Are you currently taking a statin (e.g. atorvastatin, rosuvastatin, simvastatin)?",
    description: "Statins can deplete CoQ10; this changes which supplements may be relevant.",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "medication_profile", excludes: ["no"] }],
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "specific_medications",
    section: "safety",
    title: "Are you taking any of these specific medications?",
    description: "Select all that apply. We surface absorption-timing notes and B-vitamin depletion guidance when these are flagged.",
    maxSelections: 8,
    required: true,
    showWhen: [{ questionId: "medication_profile", excludes: ["no"] }],
    options: [
      {
        value: "med_levothyroxine",
        label: "Levothyroxine or another thyroid hormone",
        description: "Synthroid, Eltroxin, generic levothyroxine, liothyronine.",
      },
      {
        value: "med_ppi",
        label: "Proton-pump inhibitor (regular use)",
        description:
          "Omeprazole, lansoprazole, esomeprazole, pantoprazole, rabeprazole.",
      },
      {
        value: "med_metformin",
        label: "Metformin",
      },
      {
        value: "med_ssri_serotonergic",
        label: "SSRI, SNRI, MAOI, tramadol, triptan, or lithium",
        description: "Anything serotonergic — affects which botanicals we can include.",
      },
      {
        value: "med_statin",
        label: "Statin",
        description: "Atorvastatin, rosuvastatin, simvastatin, pravastatin, others.",
      },
      {
        value: "med_glucose_lowering",
        label: "Glucose-lowering medication other than metformin",
        description: "Insulin, sulfonylureas, SGLT2 inhibitors, GLP-1 agonists.",
      },
      {
        value: "med_immunosuppressant",
        label: "Immunosuppressant",
        description:
          "Cyclosporine, tacrolimus, mycophenolate, methotrexate, biologics.",
      },
      {
        value: "med_none_of_these",
        label: "None of these",
      },
    ],
  },
  {
    id: "kidney_history",
    section: "safety",
    title: "Have you ever been told you have kidney disease or reduced kidney function?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "liver_history",
    section: "safety",
    title: "Have you ever been told you have liver disease or abnormal liver function?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "thyroid_disorder",
    section: "safety",
    title: "Do you have a thyroid disorder?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "autoimmune_condition",
    section: "safety",
    title: "Do you have an autoimmune condition?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "kidney_stones",
    section: "safety",
    title: "Do you have a history of kidney stones?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "red_flag_symptoms",
    section: "safety",
    title: "Are you currently experiencing any of the following?",
    description:
      "These can indicate conditions that need a clinical work-up before any supplement plan. If anything below applies, the most important next step is to speak with a doctor — not to add or change supplements. Pick all that apply, or 'None of the above'.",
    maxSelections: 9,
    required: true,
    options: [
      { value: "rf_chest_pain", label: "New or worsening chest pain or pressure, or pain that radiates to the arm or jaw" },
      { value: "rf_blood_in_stool", label: "Blood in stool, black/tarry stool, or a recent change in bowel habit" },
      { value: "rf_blood_in_urine", label: "Blood in urine" },
      { value: "rf_unintentional_weight_loss", label: "Unintentional weight loss of 5% or more in the last 6 months" },
      { value: "rf_suicidal_thoughts", label: "Thoughts of harming myself or that life isn't worth living" },
      { value: "rf_severe_persistent_headache", label: "A severe or persistent new headache, or 'worst headache of my life'" },
      { value: "rf_neurological_symptoms", label: "Sudden weakness, numbness, vision change, slurred speech, or balance loss" },
      { value: "rf_breast_lump", label: "A new breast lump or breast change" },
      { value: "rf_persistent_fever", label: "Fever lasting more than 3 days without obvious cause" },
      { value: "no_red_flags", label: "None of these" },
    ],
  },
  {
    id: "ssri_or_serotonergic_use",
    section: "safety",
    title: "Do you take an antidepressant, anti-anxiety, or migraine medication?",
    description:
      "SSRIs/SNRIs/MAOIs/tramadol/triptans/lithium interact with several botanicals (saffron, rhodiola, 5-HTP, SAM-e, St John's Wort) and can raise serotonin syndrome risk.",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "medication_profile", excludes: ["no"] }],
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "glucose_lowering_med",
    section: "safety",
    title: "Do you take medication for type-2 diabetes or blood-sugar control?",
    description:
      "Metformin, sulfonylureas, insulin, GLP-1 agonists. Several supplements (berberine, gymnema, fenugreek, cinnamon, ALA, chromium) can lower blood sugar further and stack the hypoglycemia risk.",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "medication_profile", excludes: ["no"] }],
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "daily_aspirin_or_nsaid",
    section: "safety",
    title: "Do you take daily low-dose aspirin or daily NSAIDs (ibuprofen, naproxen, diclofenac)?",
    description:
      "Daily aspirin and chronic NSAIDs increase bleeding risk. They affect the same supplement screens as prescription blood thinners.",
    maxSelections: 1,
    required: true,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "not_sure", label: "Not sure" },
    ],
  },
  {
    id: "blood_pressure_status",
    section: "safety",
    title: "What's your current blood pressure picture?",
    description:
      "Affects which supplements can interact with antihypertensives, and which lifestyle interventions get prioritized.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "bp_unknown", label: "I don't know my blood pressure" },
      { value: "bp_normal", label: "Normal" },
      { value: "bp_borderline", label: "Borderline / pre-hypertension" },
      { value: "bp_high_treated", label: "High, treated with medication" },
      { value: "bp_high_untreated", label: "High, not currently treated" },
    ],
  },
  {
    id: "glucose_status",
    section: "labs",
    title: "If you have recent fasting glucose or HbA1c results, what did they show?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "none", label: "No recent test" },
      { value: "normal", label: "Normal" },
      { value: "borderline_low", label: "Borderline / pre-diabetic" },
      { value: "high", label: "Diabetic range" },
    ],
  },
  {
    id: "lipid_status",
    section: "labs",
    title: "If you have recent total or LDL cholesterol results, what did they show?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "none", label: "No recent test" },
      { value: "normal", label: "Normal" },
      { value: "borderline_low", label: "Borderline" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "known_allergies",
    section: "safety",
    title: "Any known food or supplement allergies?",
    description:
      "Pick all that apply. We use this to filter omega-3 (fish/shellfish), bee products, soy isoflavones, and peanut-derived items.",
    maxSelections: 9,
    required: false,
    options: [
      { value: "allergy_fish", label: "Fish" },
      { value: "allergy_shellfish", label: "Shellfish (incl. krill)" },
      { value: "allergy_soy", label: "Soy" },
      { value: "allergy_peanut", label: "Peanut" },
      { value: "allergy_treenut", label: "Tree nuts" },
      { value: "allergy_bee_products", label: "Bee products (royal jelly, propolis)" },
      { value: "allergy_dairy", label: "Dairy" },
      { value: "allergy_egg", label: "Egg" },
      { value: "no_known_allergies", label: "I have no known allergies" },
    ],
  },
  {
    id: "existing_supplements",
    section: "safety",
    title: "Which supplements are you already taking?",
    description:
      "Pick all that apply. We use this to avoid recommending an additional dose of something you're already getting — vitamin A, D, niacin, iron, zinc, selenium, iodine, and B6 all have upper-tolerable-intake levels worth respecting.",
    maxSelections: 12,
    required: false,
    options: [
      { value: "supp_multivitamin", label: "A daily multivitamin" },
      { value: "supp_vitamin_d", label: "Vitamin D" },
      { value: "supp_iron", label: "Iron" },
      { value: "supp_zinc", label: "Zinc" },
      { value: "supp_calcium", label: "Calcium" },
      { value: "supp_b_complex", label: "B-complex or individual B-vitamins" },
      { value: "supp_vitamin_a", label: "Vitamin A or beta-carotene" },
      { value: "supp_selenium", label: "Selenium" },
      { value: "supp_iodine", label: "Iodine" },
      { value: "supp_omega3", label: "Fish oil / omega-3" },
      { value: "supp_other", label: "Other supplements not listed" },
      { value: "no_existing_supplements", label: "I'm not taking any supplements" },
    ],
  },
  {
    id: "diet_pattern",
    section: "lifestyle",
    title: "Which eating pattern fits you best?",
    maxSelections: 1,
    required: true,
    options: [
      {
        value: "vegan",
        label: "Vegan",
        description: "No animal products — no meat, fish, dairy, or eggs.",
      },
      {
        value: "vegetarian",
        label: "Vegetarian",
        description: "No meat or fish, but dairy and eggs are fine.",
      },
      {
        value: "pescatarian",
        label: "Pescatarian",
        description: "No meat, but fish and seafood, dairy, and eggs are fine.",
      },
      {
        value: "low_carb_high_fat",
        label: "Low carb high fat (LCHF)",
        description: "Carbs kept low (typically under ~100 g/day), most calories from fat and protein. Includes keto.",
      },
      {
        value: "carnivore",
        label: "Carnivore",
        description: "Mostly animal foods (meat, fish, eggs, sometimes dairy). Almost no plants.",
      },
      {
        value: "omnivore",
        label: "Omnivore",
        description: "A mix of everything — meat, fish, plants, grains, dairy. The default Western pattern.",
      },
    ],
  },
  {
    id: "fish_intake",
    section: "lifestyle",
    title: "How often do you eat oily fish or seafood?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "rarely", label: "Rarely or never" },
      { value: "weekly", label: "About once a week" },
      { value: "most_days", label: "Several times a week" },
      { value: "daily", label: "Almost daily" },
    ],
  },
  {
    id: "red_meat_intake",
    section: "lifestyle",
    title: "How often do you eat red meat?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "rarely", label: "Rarely or never" },
      { value: "weekly", label: "About once a week" },
      { value: "most_days", label: "Several times a week" },
      { value: "daily", label: "Almost daily" },
    ],
  },
  {
    id: "dairy_intake",
    section: "lifestyle",
    title: "How often do you have dairy or fortified dairy alternatives?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "rarely", label: "Rarely or never" },
      { value: "weekly", label: "A few times a week" },
      { value: "most_days", label: "Most days" },
      { value: "daily", label: "Daily" },
    ],
  },
  {
    id: "sun_exposure",
    section: "lifestyle",
    title: "How much regular midday sun exposure do you usually get?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "none_or_low", label: "Very little" },
      { value: "moderate", label: "Some" },
      { value: "high", label: "A lot" },
    ],
  },
  {
    id: "alcohol_units_weekly",
    section: "lifestyle",
    title: "Roughly how many units of alcohol do you drink per week?",
    description:
      "1 UK unit = 8 g pure alcohol ≈ a small (125 ml) glass of wine, half a pint of regular-strength beer, or a 25 ml spirit. A US \"standard drink\" is 14 g alcohol ≈ 1.75 UK units, so 8 US drinks/week ≈ 14 UK units (the UK low-risk threshold). Convert your US drinks to UK units before answering.",
    maxSelections: 1,
    required: true,
    options: [
      { value: "alc_zero", label: "I don't drink" },
      { value: "alc_1_to_7", label: "1 to 7 units" },
      { value: "alc_8_to_14", label: "8 to 14 units" },
      { value: "alc_15_to_21", label: "15 to 21 units" },
      { value: "alc_22_to_35", label: "22 to 35 units" },
      { value: "alc_35_plus", label: "More than 35 units" },
    ],
  },
  {
    id: "alcohol_binge_frequency",
    section: "lifestyle",
    title: "How often do you have 5+ drinks (men) or 4+ drinks (women) in a single sitting?",
    description:
      "Binge episodes drive cardiovascular events, AFib, and injury risk independently of weekly total.",
    maxSelections: 1,
    required: false,
    showWhen: [{ questionId: "alcohol_units_weekly", excludes: ["alc_zero"] }],
    options: [
      { value: "binge_never", label: "Never" },
      { value: "binge_monthly", label: "Monthly or less" },
      { value: "binge_weekly", label: "About weekly" },
      { value: "binge_multiple_weekly", label: "Multiple times per week" },
    ],
  },
  {
    id: "tobacco_use",
    section: "lifestyle",
    title: "Tobacco / cigarette use?",
    description:
      "Smoking history affects supplement safety (e.g. beta-carotene is contraindicated in current and recent smokers) and shifts vitamin C and antioxidant requirements.",
    maxSelections: 1,
    required: true,
    options: [
      { value: "smoking_never", label: "Never smoked" },
      { value: "smoking_former_remote", label: "Former smoker (quit more than 10 years ago)" },
      { value: "smoking_former_recent", label: "Former smoker (quit within 10 years)" },
      { value: "smoking_current_light", label: "Current smoker, less than 10 / day" },
      { value: "smoking_current_heavy", label: "Current smoker, 10 or more / day" },
    ],
  },
  {
    id: "vaping_use",
    section: "lifestyle",
    title: "Do you vape or use e-cigarettes?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "vaping_no", label: "No" },
      { value: "vaping_occasional", label: "Occasionally" },
      { value: "vaping_daily", label: "Daily" },
    ],
  },
  {
    id: "fruit_veg_servings",
    section: "lifestyle",
    title: "How many servings of fruit and vegetables do you eat on a typical day?",
    description:
      "One serving ≈ 80 g, or roughly a fist. WHO and UK guidance is at least 5 servings/day (≈400 g); per-serving mortality benefit continues up to ~7–8 servings/day in long-term cohorts (Aune 2017).",
    maxSelections: 1,
    required: true,
    options: [
      { value: "fv_zero_to_1", label: "0 to 1 serving" },
      { value: "fv_2_to_3", label: "2 to 3 servings" },
      { value: "fv_4", label: "4 servings" },
      { value: "fv_5_to_7", label: "5 to 7 servings" },
      { value: "fv_8_plus", label: "8 or more servings" },
    ],
  },
  {
    id: "fibre_intake",
    section: "lifestyle",
    title: "How often do you eat wholegrains or legumes (beans, lentils, oats, brown rice, wholegrain bread)?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "fibre_rarely", label: "Rarely or never" },
      { value: "fibre_some_days", label: "A few times a week" },
      { value: "fibre_most_days", label: "Most days" },
      { value: "fibre_daily", label: "Daily" },
    ],
  },
  {
    id: "ssb_intake",
    section: "lifestyle",
    title: "Sugar-sweetened drinks per day (sodas, sweetened coffee, fruit juice, sweet tea, energy drinks)?",
    description:
      "Liquid sugar bypasses satiety regulation. Each daily 12-oz/350 ml serving raises type-2 diabetes risk ~18% in long-term cohorts.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "ssb_zero", label: "None" },
      { value: "ssb_one", label: "About 1 per day" },
      { value: "ssb_two_to_three", label: "2 to 3 per day" },
      { value: "ssb_four_plus", label: "4 or more per day" },
    ],
  },
  {
    id: "ultra_processed_intake",
    section: "lifestyle",
    title: "Roughly what share of your daily food is ultra-processed?",
    description:
      "Ultra-processed foods are industrial formulations with ingredients you wouldn't have in a home kitchen — colourings, emulsifiers, flavour enhancers, hydrogenated oils, high-fructose syrups. Common examples: soft drinks and energy drinks, packaged snacks (crisps, biscuits, sweets), most breakfast cereals, flavoured yogurts, sliced packaged bread, instant noodles, deli meats and reconstituted meats (hot dogs, nuggets), ready meals, mass-market ice cream, sweetened plant milks. Not UPF: plain bread from a baker, plain yogurt, tinned beans/tomatoes, frozen vegetables, cheese, butter, plain meat and fish. Umbrella reviews (Lane et al. 2024, BMJ) link high intake to higher all-cause mortality, cardiovascular disease, type-2 diabetes, and depression.",
    maxSelections: 1,
    required: false,
    options: [
      {
        value: "upf_minimal",
        label: "Very little",
        description: "Mostly whole or home-cooked foods — packaged ready meals and snacks are rare.",
      },
      {
        value: "upf_some",
        label: "Some",
        description: "Maybe a quarter of what I eat — occasional packaged snacks, sweetened drinks, or convenience meals.",
      },
      {
        value: "upf_about_half",
        label: "About half",
        description: "Roughly a 50/50 mix of home-style food and packaged or fast food.",
      },
      {
        value: "upf_most",
        label: "Most of what I eat",
        description: "Most meals come from packaged, convenience, or fast-food sources.",
      },
    ],
  },
  {
    id: "water_intake",
    section: "holistic",
    title: "About how much water do you drink per day?",
    description: "Rough guess is fine. Coffee and tea count toward hydration.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "lt_1l", label: "Less than 1 litre" },
      { value: "1_to_2l", label: "1 to 2 litres" },
      { value: "2_to_3l", label: "2 to 3 litres" },
      { value: "gt_3l", label: "More than 3 litres" },
    ],
  },
  {
    id: "sleep_hours",
    section: "holistic",
    title: "On a typical night, how many hours do you sleep?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "lt_6h", label: "Less than 6 hours" },
      { value: "6_to_7h", label: "6 to 7 hours" },
      { value: "7_to_8h", label: "7 to 8 hours" },
      { value: "gt_8h", label: "More than 8 hours" },
    ],
  },
  {
    id: "sitting_hours",
    section: "holistic",
    title: "On a typical day, how many hours do you spend sitting?",
    description: "Includes desk, car, sofa — anything where you're sitting still.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "lt_4h", label: "Less than 4 hours" },
      { value: "4_to_8h", label: "4 to 8 hours" },
      { value: "8_to_12h", label: "8 to 12 hours" },
      { value: "gt_12h", label: "More than 12 hours" },
    ],
  },
  {
    id: "screen_hours",
    section: "holistic",
    title: "Hours per day in front of a screen (work + leisure)?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "lt_4h", label: "Less than 4 hours" },
      { value: "4_to_8h", label: "4 to 8 hours" },
      { value: "8_to_12h", label: "8 to 12 hours" },
      { value: "gt_12h", label: "More than 12 hours" },
    ],
  },
  {
    id: "social_connection",
    section: "holistic",
    title: "How much in-person time do you get with friends or family?",
    description: "Loneliness has bigger effects on health than most supplements; we factor it in.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "isolated", label: "Almost none" },
      { value: "limited", label: "A few times a month" },
      { value: "regular", label: "A few times a week" },
      { value: "abundant", label: "Most days" },
    ],
  },
  {
    id: "time_in_nature",
    section: "holistic",
    title: "How often do you spend time outdoors or in nature?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "almost_never", label: "Almost never" },
      { value: "weekly_outdoors", label: "Weekly" },
      { value: "daily_outdoors", label: "Daily, even briefly" },
    ],
  },
  {
    id: "weight_band",
    section: "holistic",
    title: "Roughly, what's your weight category?",
    description: "Honest estimate is fine. We use this for nutrient adequacy, not aesthetics.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "underweight_band", label: "Underweight" },
      { value: "healthy_band", label: "Healthy weight" },
      { value: "overweight_band", label: "Overweight" },
      { value: "obese_band", label: "Significantly overweight" },
    ],
  },
  {
    id: "weight_change_recent",
    section: "holistic",
    title: "Has your weight changed meaningfully in the last 6 months?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "lost_weight", label: "Lost weight" },
      { value: "stable_weight", label: "Roughly stable" },
      { value: "gained_weight", label: "Gained weight" },
    ],
  },
  {
    id: "cardio_minutes_weekly",
    section: "holistic",
    title: "Roughly, how many minutes of cardio do you do per week?",
    description: "Anything that gets your heart rate up — walking briskly, cycling, swimming, jogging.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "lt_60_min", label: "Less than 60 minutes" },
      { value: "60_to_150_min", label: "60 to 150 minutes" },
      { value: "150_to_300_min", label: "150 to 300 minutes" },
      { value: "gt_300_min", label: "More than 300 minutes" },
    ],
  },
  {
    id: "strength_sessions_weekly",
    section: "holistic",
    title: "How many strength training sessions per week?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "zero_strength", label: "None" },
      { value: "one_strength", label: "1 session" },
      { value: "two_three_strength", label: "2 to 3 sessions" },
      { value: "four_plus_strength", label: "4 or more sessions" },
    ],
  },
  {
    id: "daily_steps",
    section: "holistic",
    title: "Daily steps on a typical day?",
    description: "Best guess if you don't track them.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "lt_5k", label: "Less than 5,000" },
      { value: "5k_to_8k", label: "5,000 to 8,000" },
      { value: "8k_to_12k", label: "8,000 to 12,000" },
      { value: "gt_12k", label: "More than 12,000" },
    ],
  },
  {
    id: "bedtime_consistency",
    section: "holistic",
    title: "How consistent is your bedtime?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "very_consistent", label: "Within 30 minutes most nights" },
      { value: "mostly_consistent", label: "Within an hour most nights" },
      { value: "irregular", label: "Varies widely" },
    ],
  },
  {
    id: "awakenings",
    section: "holistic",
    title: "Do you wake during the night?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "no_awakenings", label: "Rarely / sleep through" },
      { value: "occasional_awakenings", label: "Occasionally" },
      { value: "frequent_awakenings", label: "Most nights, several times" },
    ],
  },
  {
    id: "snoring_pattern",
    section: "holistic",
    title: "Do you snore loudly, or have you been told you stop breathing in your sleep?",
    description: "Loud snoring or witnessed pauses can indicate sleep apnea — supplements aren't the answer here.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "no_snoring", label: "No / quiet" },
      { value: "occasional_snoring", label: "Occasional snoring" },
      { value: "loud_snoring_or_apnea", label: "Loud snoring or witnessed pauses" },
    ],
  },
  {
    id: "caffeine_cutoff",
    section: "holistic",
    title: "When do you have your last caffeine of the day?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "no_caffeine", label: "I don't have caffeine" },
      { value: "before_noon", label: "Before noon" },
      { value: "noon_to_3pm", label: "Noon to 3pm" },
      { value: "after_3pm", label: "After 3pm" },
    ],
  },
  {
    id: "cycle_pattern",
    section: "holistic",
    title: "How would you describe your menstrual cycle?",
    maxSelections: 1,
    required: false,
    showWhen: [{ questionId: "sex", includes: ["female"] }],
    options: [
      { value: "regular_cycle", label: "Regular" },
      { value: "irregular_cycle", label: "Irregular" },
      { value: "no_cycle", label: "Not currently menstruating" },
      { value: "post_menopause", label: "Post-menopause" },
    ],
  },
  {
    id: "pms_pattern",
    section: "holistic",
    title: "Do you experience PMS symptoms?",
    maxSelections: 1,
    required: false,
    showWhen: [
      { questionId: "sex", includes: ["female"] },
      { questionId: "cycle_pattern", includes: ["regular_cycle", "irregular_cycle"] },
    ],
    options: [
      { value: "no_pms", label: "No / minimal" },
      { value: "mild_pms", label: "Mild" },
      { value: "significant_pms", label: "Significant" },
    ],
  },
  {
    id: "perimenopause_symptoms",
    section: "holistic",
    title: "Are you experiencing perimenopause symptoms?",
    description: "Hot flashes, night sweats, cycle changes, mood shifts.",
    maxSelections: 1,
    required: false,
    showWhen: [
      { questionId: "sex", includes: ["female"] },
      { questionId: "age_band", includes: ["45_59", "60_69", "70_79", "80_plus"] },
    ],
    options: [
      { value: "no_perimenopause", label: "No" },
      { value: "hot_flashes", label: "Mainly hot flashes / night sweats" },
      { value: "perimenopause_mixed", label: "Multiple symptoms" },
    ],
  },
  {
    id: "contraception_type",
    section: "holistic",
    title: "What type of contraception, if any, are you using?",
    description: "This affects which botanicals interact and a few nutrient priorities.",
    maxSelections: 1,
    required: false,
    showWhen: [
      { questionId: "sex", includes: ["female"] },
      { questionId: "cycle_pattern", includes: ["regular_cycle", "irregular_cycle", "no_cycle"] },
    ],
    options: [
      { value: "none_birth_control", label: "None" },
      { value: "combined_pill", label: "Combined pill" },
      { value: "progestin_only", label: "Progestin-only" },
      { value: "hormonal_iud", label: "Hormonal IUD" },
      { value: "non_hormonal", label: "Non-hormonal (copper IUD, barrier, etc.)" },
    ],
  },
  {
    id: "sleep_quality",
    section: "lifestyle",
    title: "How would you rate your sleep lately?",
    maxSelections: 1,
    required: true,
    showWhen: [
      { questionId: "primary_goal", includes: ["sleep", "energy", "stress"] },
    ],
    options: [
      { value: "poor", label: "Poor" },
      { value: "fair", label: "Fair" },
      { value: "good", label: "Good" },
      { value: "very_good", label: "Very good" },
    ],
  },
  {
    id: "stress_load",
    section: "lifestyle",
    title: "How would you rate your stress load lately?",
    maxSelections: 1,
    required: true,
    showWhen: [
      { questionId: "primary_goal", includes: ["stress", "sleep", "energy"] },
    ],
    options: [
      { value: "none_or_low", label: "Low" },
      { value: "moderate", label: "Moderate" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "exercise_pattern",
    section: "lifestyle",
    title: "Which activity pattern fits you best?",
    maxSelections: 1,
    required: true,
    options: [
      { value: "strength_power", label: "Strength or power training" },
      { value: "endurance", label: "Endurance training" },
      { value: "mixed_training", label: "Mixed training" },
      { value: "light_activity", label: "Light activity" },
      { value: "mostly_sedentary", label: "Mostly sedentary" },
    ],
  },
  // The next five questions are required *if visible*. Visibility is gated by
  // showWhen on primary_goal; getVisibleQuestions() runs the showWhen filter
  // before any required check, so a user whose primary_goal does not match
  // never sees these questions and is not blocked by the required flag.
  {
    id: "sleep_issue",
    section: "symptoms",
    title: "Which sleep issue fits best?",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "primary_goal", includes: ["sleep"] }],
    options: [
      { value: "sleep_onset", label: "Hard to fall asleep" },
      { value: "sleep_maintenance", label: "Wake during the night" },
      { value: "non_restorative_sleep", label: "Sleep but do not feel restored" },
      { value: "no_specific_issue", label: "None of these — I'm here for upside, not a fix" },
    ],
  },
  {
    id: "energy_issue",
    section: "symptoms",
    title: "Which energy issue fits best?",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "primary_goal", includes: ["energy"] }],
    options: [
      { value: "low_energy", label: "Low energy" },
      { value: "poor_focus", label: "Poor focus" },
      { value: "low_motivation", label: "Low motivation" },
      { value: "no_specific_issue", label: "None of these — I'm here for upside, not a fix" },
    ],
  },
  {
    id: "cognitive_bottleneck",
    section: "symptoms",
    title: "Where does your brain let you down most?",
    description: "Pick the pattern that affects you most often. We use this to choose between very different cognitive supplements.",
    maxSelections: 1,
    required: true,
    showWhen: [
      { questionId: "primary_goal", includes: ["cognitive_performance", "cognitive_longevity"] },
    ],
    options: [
      { value: "afternoon_dip", label: "Afternoon dip after lunch" },
      { value: "morning_startup", label: "Slow to get going in the morning" },
      { value: "post_meal_fog", label: "Brain fog after meals" },
      { value: "context_switching", label: "Hard to switch tasks or hold details" },
      { value: "deep_focus_stamina", label: "Can't sustain deep focus long enough" },
      { value: "memory_recall", label: "Memory and word recall feel slower" },
      { value: "stress_induced_fog", label: "Stress or anxiety eats my working memory" },
      { value: "no_specific_bottleneck", label: "Nothing specific — general optimisation" },
    ],
  },
  {
    id: "recovery_issue",
    section: "symptoms",
    title: "Which training or recovery issue fits best?",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "primary_goal", includes: ["performance"] }],
    options: [
      { value: "muscle_soreness", label: "Muscle soreness" },
      { value: "poor_recovery", label: "Poor recovery between sessions" },
      { value: "cramps", label: "Cramping" },
      { value: "no_specific_issue", label: "None of these — I'm here for upside, not a fix" },
    ],
  },
  {
    id: "gut_issue",
    section: "symptoms",
    title: "Which gut issue fits best?",
    maxSelections: 1,
    required: true,
    showWhen: [{ questionId: "primary_goal", includes: ["gut_support"] }],
    options: [
      { value: "bloating", label: "Bloating" },
      { value: "constipation", label: "Constipation" },
      { value: "diarrhea", label: "Loose stools or diarrhea" },
      { value: "post_antibiotic_recovery", label: "Post-antibiotic recovery" },
      { value: "no_specific_issue", label: "None of these — I'm here for upside, not a fix" },
    ],
  },
  {
    id: "bowel_pattern",
    section: "symptoms",
    title: "How often do you typically have a bowel movement?",
    description:
      "Helpful for spotting constipation patterns and as a general signal of fibre and hydration status.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "bowel_less_than_3_per_week", label: "Less than 3 times per week" },
      { value: "bowel_3_to_6_per_week", label: "3 to 6 times per week" },
      { value: "bowel_1_to_2_per_day", label: "1 to 2 times per day" },
      { value: "bowel_3_plus_per_day", label: "3 or more times per day" },
    ],
  },
  {
    id: "gi_symptoms",
    section: "symptoms",
    title: "Do you have any of these gut/digestive symptoms regularly?",
    description: "Pick all that apply.",
    maxSelections: 6,
    required: false,
    options: [
      { value: "gi_bloating", label: "Bloating" },
      { value: "gi_reflux", label: "Reflux or heartburn" },
      { value: "gi_abdominal_pain", label: "Abdominal pain or cramping" },
      { value: "gi_alternating_constipation_diarrhea", label: "Alternating constipation and diarrhea" },
      { value: "gi_excessive_gas", label: "Excessive gas" },
      { value: "no_gi_symptoms", label: "None of these" },
    ],
  },
  {
    id: "joint_stiffness",
    section: "symptoms",
    title: "How would you describe joint stiffness or discomfort?",
    maxSelections: 1,
    required: true,
    showWhen: [
      { questionId: "primary_goal", includes: ["joint_mobility", "healthy_aging", "performance"] },
    ],
    options: [
      { value: "morning_stiffness", label: "Stiff in the morning, eases with movement" },
      { value: "post_exercise_stiffness", label: "Stiff or sore after exercise" },
      { value: "persistent_joint_pain", label: "Persistent joint pain" },
      { value: "no_joint_issue", label: "No joint issue" },
    ],
  },
  {
    id: "migraine_pattern",
    section: "symptoms",
    title: "Do you get migraines?",
    description: "Useful because riboflavin, magnesium, and CoQ10 have evidence in migraine prevention.",
    maxSelections: 1,
    required: false,
    options: [
      { value: "no", label: "No / rarely" },
      { value: "occasional_migraine", label: "Occasionally (1–3 per month)" },
      { value: "frequent_migraine", label: "Frequently (4+ per month)" },
    ],
  },
  {
    id: "nail_signs",
    section: "body_signs",
    title: "Have you noticed anything unusual about your nails lately?",
    description:
      "Pick anything that applies. Nails can hint at low iron, zinc, or B vitamins — though some changes are just from age or occupation.",
    maxSelections: 5,
    required: false,
    options: [
      { value: "nail_white_spots", label: "White spots or specks" },
      { value: "nail_ridges_horizontal", label: "Horizontal ridges or grooves across the nail" },
      { value: "nail_spoon_shaped", label: "Concave or spoon-shaped nails (curve up at the edges)" },
      { value: "nail_brittle_peeling", label: "Brittle, peeling, or splitting easily" },
      { value: "nail_pale_beds", label: "Pale nail beds (compared to a few years ago)" },
      { value: "no_nail_signs", label: "None of these" },
    ],
  },
  {
    id: "skin_signs",
    section: "body_signs",
    title: "Anything going on with your skin?",
    description:
      "Pick anything that applies. Skin signs can point to omega-3, zinc, or B-vitamin status, among others.",
    maxSelections: 6,
    required: false,
    options: [
      { value: "skin_dry_scaly", label: "Persistently dry, flaky, or scaly patches" },
      { value: "skin_eczema_inflamed", label: "Red, inflamed, or eczema-like patches" },
      { value: "skin_adult_acne", label: "Adult acne (not teenage hormonal acne)" },
      { value: "skin_easy_bruising", label: "Bruise more easily than seems normal" },
      { value: "skin_slow_healing", label: "Cuts and scrapes are slow to heal" },
      { value: "skin_pale_sallow", label: "Skin looks pale or sallow" },
      { value: "no_skin_signs", label: "None of these" },
    ],
  },
  {
    id: "hair_signs",
    section: "body_signs",
    title: "Any changes in your hair?",
    description:
      "Pick anything that applies. We separate diffuse changes (often nutritional) from patterned changes (usually genetic) so we don't promise things supplements can't deliver.",
    maxSelections: 5,
    required: false,
    options: [
      { value: "hair_diffuse_shedding", label: "Diffuse thinning or shedding all over the scalp (not a receding hairline or crown)" },
      { value: "hair_dry_brittle", label: "Hair feels dry, brittle, or breaks easily" },
      { value: "hair_premature_greying", label: "Premature greying — earlier than others in your family" },
      { value: "hair_pattern_loss_genetic", label: "Receding hairline, crown thinning, or a family pattern of hair loss" },
      { value: "hair_familial_early_greying", label: "Greying that runs strongly in my family" },
      { value: "no_hair_signs", label: "None of these" },
    ],
  },
  {
    id: "mouth_signs",
    section: "body_signs",
    title: "Anything going on with your mouth, tongue, or gums?",
    description:
      "These are some of the more specific deficiency signs in nutrition science.",
    maxSelections: 4,
    required: false,
    options: [
      { value: "mouth_cracks_corners", label: "Cracks or sores at the corners of the mouth" },
      { value: "mouth_sore_smooth_tongue", label: "Sore, red, or unusually smooth tongue" },
      { value: "mouth_bleeding_gums", label: "Gums bleed easily when brushing or flossing" },
      { value: "no_mouth_signs", label: "None of these" },
    ],
  },
  {
    id: "other_signs",
    section: "body_signs",
    title: "Any of these other signals?",
    description: "Often-overlooked signs that map cleanly to specific nutrients.",
    maxSelections: 6,
    required: false,
    options: [
      { value: "cold_extremities", label: "Hands and feet that feel cold a lot of the time" },
      { value: "muscle_twitches_restless_legs", label: "Muscle twitches, cramps at rest, or restless legs at night" },
      { value: "taste_smell_changes", label: "Taste or smell feels duller than it used to" },
      { value: "frequent_infections", label: "Catch every cold going around, or slow to recover from them" },
      { value: "poor_night_vision", label: "Difficulty seeing well in low light or at night" },
      { value: "no_other_signs", label: "None of these" },
    ],
  },
  {
    id: "lab_vitamin_d_status",
    section: "labs",
    title: "If you have recent vitamin D labs, what did they show?",
    maxSelections: 1,
    required: false,
    options: [
      { value: "none", label: "No recent test" },
      { value: "known_low", label: "Low" },
      { value: "borderline_low", label: "Borderline low" },
      { value: "normal", label: "Normal" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "lab_ferritin_status",
    section: "labs",
    title: "If you have recent iron or ferritin labs, what did they show?",
    maxSelections: 1,
    required: false,
    showWhen: [
      { questionId: "primary_goal", includes: ["energy", "general_nutrition"] },
    ],
    options: [
      { value: "none", label: "No recent test" },
      { value: "known_low", label: "Low" },
      { value: "borderline_low", label: "Borderline low" },
      { value: "normal", label: "Normal" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "lab_b12_status",
    section: "labs",
    title: "If you have recent B12 labs, what did they show?",
    maxSelections: 1,
    required: false,
    showWhen: [
      { questionId: "diet_pattern", includes: ["vegan", "vegetarian"] },
    ],
    options: [
      { value: "none", label: "No recent test" },
      { value: "known_low", label: "Low" },
      { value: "borderline_low", label: "Borderline low" },
      { value: "normal", label: "Normal" },
      { value: "high", label: "High" },
    ],
  },
  {
    id: "lab_triglycerides_status",
    section: "labs",
    title: "If you have recent triglyceride labs, what did they show?",
    maxSelections: 1,
    required: false,
    showWhen: [
      {
        questionId: "primary_goal",
        includes: ["general_nutrition", "healthy_aging", "immune_support"],
      },
    ],
    options: [
      { value: "none", label: "No recent test" },
      { value: "known_low", label: "Below range" },
      { value: "borderline_low", label: "Borderline" },
      { value: "normal", label: "Normal" },
      { value: "high", label: "High" },
    ],
  },
];
